title: Jochen Jacobs
description: Welcome to my personal homepage!
show_downloads: true

baseurl: "" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://jacobsjo.eu" # change this to the base hostname & protocol for your site


google_analytics:

# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

github:
  is_project_page: false

# social
author: Jochen Jacobs
image: /thumbnail-jumbo.png
twitter:
  username: jacobsjo_


target-blank:
    rel: nofollow

header_page_refs: ['photos', 'contact']
